# Generated by Django 4.1.7 on 2023-03-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='problem_number',
            field=models.IntegerField(default=1000),
        ),
    ]
