# Generated by Django 4.1.7 on 2023-03-26 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_problem_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='introduce',
            new_name='problem_introduce',
        ),
    ]
