# Generated by Django 4.1.7 on 2023-03-26 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_introduce_blog_problem_introduce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='problem_introduce',
            new_name='problem_text',
        ),
    ]
